{% set name = "configobj" %}
{% set version = "5.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/configobj-{{ version }}.tar.gz
  sha256: a4f856ffc73ebbc44c3830326a7c75ddcdb5941216030fc2115220e913a9939d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - six

test:
  imports:
    - configobj
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DiffSK/configobj
  summary: Config file reading, writing and validation.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
