{% set version = "5.0.7" %}

package:
  name: configobj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/configobj/configobj-{{ version }}.tar.gz
  sha256: a4f856ffc73ebbc44c3830326a7c75ddcdb5941216030fc2115220e913a9939d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - python
    - six
  run:
    - python
    - six

test:
  imports:
    - configobj

about:
  home: https://github.com/DiffSK/configobj
  license: BSD-3-Clause
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Config file reading, writing and validation

extra:
  recipe-maintainers:
    - ocefpaf
