travis:
  secure:
    BINSTAR_TOKEN: qkL7AUoPV9at4UYHNKhwgMys4VmBKNDRt6l+wQXD7VpTALw59cPafF121mRavdHbNqt5e/Wy1ZqHw/f5HdFfR098MJvxR8ck8xU1A24yUPOuBlsiRW5UlUUYKuUH3P97kqKHiRKr5bWphtFvuUO9zCt4ebQnBKU6z38BSF3HlmN5327gJkmYsFNoQomi9l0M7yayoM2CjNdIhdjYycMWpfRPOJH6a8BSIv9ygWs/t2NYH1/5wdkBTpdbslUCLbkXdjMYWik0oNFxkIEUX9scPxqE0VfwhtbkbPibHgLVCaaTR/kLCZt6W0piwmxFExRCm5ksgbp9ekrbO02K7ofDwQzgpWJATkkuXlEOLug/M5y7d4F82znfD9+CEC1cwvHKyt21PO3sAxFp6VV3aqa8kkd/R1JQ+UdGk5YtjtEWFBLbkMZ1J0uMM6+o2Y+UPmCp78miaWjGaVUih31SFqzEFHeTErt4msYInf8j+GSuordPrtUOaZyS3UEHFIIF1jegOMN8zNregF6zZYi758rRESx8Ysh77ZXelQbUOwZ4/hIb2IjAJjmoTSdGqDi/65vme8907878hJ8VnTN+fhXtlRPE+cfMxvQT0U+ubSGvW+G3RMUqakNKMm6kGDgPjTH9+TiKs5Ic9MggVubqv3Ub1KrxlgAgdN3kuOM7aVL5d6A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
